name: Telegram Proxy Collector

on:
  schedule:
    # اجرا هر ۳ ساعت، در دقیقه ۵
    - cron: '5 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp

    - name: Run Proxy Collector
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        PROXY_SOURCES: ${{ secrets.PROXY_SOURCES }}
      run: |
        python proxy_collector.py

    - name: Commit and Push Files to Repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add PROXIES_TG_FORMAT.txt PROXIES_HTTP_FORMAT.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update Top 100 Proxies [skip ci]" && git push)
